# syntax=docker/dockerfile:1
FROM ubuntu:24.04

ENV DEBIAN_FRONTEND=noninteractive
ENV PATH=/root/.local/bin:$PATH

RUN set -e; \
    PACKAGES="\
      ca-certificates \
      curl \
      git \
      build-essential \
      cmake \
      clang \
      clang-tools \
      clang-tidy \
      llvm \
      cppcheck \
      python3 \
      python3-venv \
      python3-pip \
      pipx \
      openjdk-17-jre \
    "; \
    apt-get update && \
    apt-get install --dry-run $PACKAGES && \
    apt-get install -y $PACKAGES && \
    rm -rf /var/lib/apt/lists/*


# ---- CodeChecker ----
RUN pipx install codechecker \
 && CodeChecker version


WORKDIR /work
